[project]
name = "raindrops-on-roses"  # name for main folder, repo, pypi, and install
version = "0.1.1.20260826"
description = "Raindrops on roses (and whiskers on kittens) - Collection of 'a few of my favourite things' -i.e. classes and functions- in order to stop repeating myself"
readme = "README.md"
authors = [ { name = "Dutcho" } ]
requires-python = ">=3.12"
dependencies = [
    "more-itertools",
    "typing_extensions",
]

[build-system]
requires = ["uv_build<1.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "favs"  # name for src subfolder and import
